version: "3"

services:
  app:
    container_name: server
    build: .
    ports:
      - 5000:5000
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      MONGO_URL:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
